apiVersion: v2
name: keda
description: KEDA event-driven autoscaler
type: application
version: 0.1.0
dependencies:
  - name: keda
    version: 2.20.2
    repository: https://kedacore.github.io/charts
