apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: webapp
  namespace: demo
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: webapp-wake
  namespace: demo
spec:
  hosts:
    - webapp-wake.internal
  location: MESH_INTERNAL
  resolution: DNS
  ports:
    - number: 80
      name: http
      protocol: HTTP
  endpoints:
    - address: webapp.demo.svc.cluster.local
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: webapp
  namespace: demo
spec:
  hosts:
    - "*"
  gateways:
    - webapp
  http:
    - route:
        - destination:
            host: webapp-wake.internal
            port:
              number: 80
      timeout: 120s
      retries:
        attempts: 100
        perTryTimeout: 1s
        retryOn: "connect-failure,refused-stream,unavailable,5xx,reset"
