apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp
  namespace: demo
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
