apiVersion: v2
name: istiod
description: Istio control plane
type: application
version: 0.1.0
dependencies:
  - name: istiod
    version: 1.30.4
    repository: https://istio-release.storage.googleapis.com/charts
