metrics-server:
  replicas: 1

  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP

  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 128Mi
